#!/usr/bin/env bash
#
# setup-asc.sh — one-time setup of App Store Connect API credentials so release.sh
# can upload to TestFlight with zero interaction from then on.
#
# You provide three things (all from App Store Connect → Users and Access → Integrations
# → App Store Connect API):
#   • Key ID        (10 chars, shown next to the key)
#   • Issuer ID     (UUID at the top of the Integrations page)
#   • the .p8 file   (downloaded ONCE when you create the key)
#
# This script copies the .p8 to ~/.appstoreconnect/private_keys/ and writes scripts/.env
# (git-ignored). Run it once; after that just use ./scripts/release.sh.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/scripts/.env"
KEY_DIR="$HOME/.appstoreconnect/private_keys"

bold()  { printf "\033[1m%s\033[0m\n" "$1"; }
green() { printf "\033[0;32m%s\033[0m\n" "$1"; }
red()   { printf "\033[0;31m%s\033[0m\n" "$1"; }

bold "App Store Connect API key setup"
echo "Get these at: https://appstoreconnect.apple.com → Users and Access → Integrations → App Store Connect API"
echo

read -r -p "Key ID (e.g. 7K9ABC1234): " KEY_ID
read -r -p "Issuer ID (UUID): " ISSUER_ID
read -r -p "Path to the .p8 file (e.g. ~/Downloads/AuthKey_7K9ABC1234.p8): " P8_INPUT

# Expand ~ and resolve.
P8_PATH="${P8_INPUT/#\~/$HOME}"
if [ ! -f "$P8_PATH" ]; then
  red "✗ File not found: $P8_PATH"
  exit 1
fi

mkdir -p "$KEY_DIR"
DEST="$KEY_DIR/AuthKey_${KEY_ID}.p8"
cp "$P8_PATH" "$DEST"
chmod 600 "$DEST"
green "✓ Stored key at $DEST"

cat > "$ENV_FILE" <<EOF
# App Store Connect API credentials (git-ignored). Generated by scripts/setup-asc.sh.
export ASC_KEY_ID="$KEY_ID"
export ASC_ISSUER_ID="$ISSUER_ID"
export ASC_KEY_PATH="$DEST"
EOF
chmod 600 "$ENV_FILE"
green "✓ Wrote $ENV_FILE"

echo
bold "Done. From now on, ship with:"
echo "  ./scripts/release.sh \"what changed\"   # builds, pushes, and uploads to TestFlight automatically"
